spring.application.name=payment-service

server.port=8081
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

stripe.api.key=${STRIPE_SECRET_KEY}


stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}